algo = input('Digite algo: ')
print('Foi digitado um ',type(algo))
print('Só tem espaço?', algo.isspace())
print('É um numero:',algo.isnumeric())
print('É alfabético :',algo.isalpha())
print('Esta em minúsculas:',algo.islower())
print('É um decimal:',algo.isdecimal())
print('É alfanumérico:',algo.isalnum())
print('Esta em maiusculas:',algo.isupper())
print('Esta capitalizada:',algo.istitle())
